export const GET_MATCHES_CLOSED_REQUEST = 'GET_MATCHES_CLOSED_REQUEST';
export const GET_MATCHES_CLOSED_SUCCESS = 'GET_MATCHES_CLOSED_SUCCESS';
export const GET_MATCHES_CLOSED_FAIL = 'GET_MATCHES_CLOSED_FAIL';