export const GET_RANKING_REQUEST = 'GET_RANKING_REQUEST';
export const GET_RANKING_SUCCESS = 'GET_RANKING_SUCCESS';
export const GET_RANKING_FAIL = 'GET_RANKING_FAIL';
export const GET_USER_RANKING_REQUEST = 'GET_USER_RANKING_REQUEST';
export const GET_USER_RANKING_SUCCESS = 'GET_USER_RANKING_SUCCESS';
export const GET_USER_RANKING_FAIL = 'GET_USER_RANKING_FAIL';