export const GET_BOARDS_REQUEST = 'GET_BOARDS_REQUEST';
export const GET_BOARDS_SUCCESS = 'GET_BOARDS_SUCCESS';
export const GET_BOARDS_FAIL = 'GET_BOARDS_FAIL';
export const SAVE_BOARDS_REQUEST = 'SAVE_BOARDS_REQUEST';
export const SAVE_BOARDS_SUCCESS = 'SAVE_BOARDS_SUCCESS';
export const SAVE_BOARDS_ERROR = 'SAVE_BOARDS_ERROR';
